backup_settings:
  destination: "<DestinationPath>"
  zip: true
  timestamp_format: "%Y%m%d_%H%M%S"
  seven_zip_path: "C:/Program Files/7-Zip/7z.exe"

tasks:
  - name: "<TaskName>"
    source: "<SourcePath>""
    run: false
  - name: "<Task2Name>""
    source: "<Source2Path>"
    run: true
